# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

  # top-level class documentation commentの除外
Documentation:
  Enabled: false

# 対象ファイル
AllCops:
  Exclude:
    - './**'
    - './bin/**'
  Include:
    - 'app/controllers/**'
    - 'app/model/**'
    - 'app/serializers/**'
    - 'test/controllers/**'
  Rails:
    Enabled: true